12-12-2015/projeto/config/routes.rb
Rails.application.routes.draw do
  resources :livros

end

12-12-2015/projeto/app/models/livro.rb
class Livro < ActiveRecord::Base
end

12-12-2015/projeto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

12-12-2015/projeto/app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: [:show, :edit, :update, :destroy]

  # GET /livros
  # GET /livros.json
  def index
    @livros = Livro.all
  end

  # GET /livros/1
  # GET /livros/1.json
  def show
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros
  # POST /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to @livro, notice: 'Livro was successfully created.' }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1
  # PATCH/PUT /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to @livro, notice: 'Livro was successfully updated.' }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1
  # DELETE /livros/1.json
  def destroy
    @livro.destroy
    respond_to do |format|
      format.html { redirect_to livros_url, notice: 'Livro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def livro_params
      params.require(:livro).permit(:titulo, :autor, :descricao)
    end
end

12-12-2015/projeto/app/helpers/application_helper.rb
module ApplicationHelper
end

12-12-2015/projeto/app/helpers/livros_helper.rb
module LivrosHelper
end

12-12-2015/projeto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projeto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

12-12-2015/projeto/app/views/livros/_form.html.erb
<%= form_for(@livro) do |f| %>
  <% if @livro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
      <% @livro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

12-12-2015/projeto/app/views/livros/edit.html.erb
<h1>Editing Livro</h1>

<%= render 'form' %>

<%= link_to 'Show', @livro %> |
<%= link_to 'Back', livros_path %>

12-12-2015/projeto/app/views/livros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listando Livros</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Autor</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @livros.each do |livro| %>
      <tr>
        <td><%= livro.titulo %></td>
        <td><%= livro.autor %></td>
        <td><%= livro.descricao %></td>
        <td><%= link_to 'Show', livro %></td>
        <td><%= link_to 'Edit', edit_livro_path(livro) %></td>
        <td><%= link_to 'Destroy', livro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Livro', new_livro_path %>

12-12-2015/projeto/app/views/livros/new.html.erb
<h1>New Livro</h1>

<%= render 'form' %>

<%= link_to 'Back', livros_path %>

12-12-2015/projeto/app/views/livros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @livro.titulo %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @livro.autor %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @livro.descricao %>
</p>

<%= link_to 'Edit', edit_livro_path(@livro) %> |
<%= link_to 'Back', livros_path %>